name: flutter_wordpress_example
description: Wordpress API testing example.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter_wordpress:
    path: ../
  flutter:
    sdk: flutter
  flutter_html: ^2.1.5

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
